name: flutter_extension
description: "Flutter extension"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  get:
  shared_preferences:
  flutter_svg:
  flutter_spinkit:
  cached_network_image:
  shimmer: 
  flutter_otp_text_field:
  country_code_picker: ^3.4.0
  image_picker: ^1.2.0
  image_cropper:
  dotted_border:
  camera: ^0.11.3
  google_mlkit_face_detection: ^0.13.1
  path_provider: ^2.1.5
  path: ^1.9.1
  mime: ^2.0.0
  flutter_html: ^3.0.0
  emoji_picker_flutter: ^4.4.0
  google_sign_in: ^6.2.2
  permission_handler: ^12.0.1
  audioplayers: ^6.6.0
  geolocator: ^14.0.2
  package_info_plus: ^8.3.1
  zego_uikit: ^2.28.44
  zego_uikit_prebuilt_call: ^4.22.3
  zego_uikit_signaling_plugin: ^2.8.20
  purchases_flutter: ^9.15.1
  purchases_ui_flutter: ^9.15.1
  onesignal_flutter: ^5.4.5
  app_badge_plus: ^1.2.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/

  fonts:
    - family: Cinzel
      fonts:
        - asset: assets/fonts/Cinzel-Black.ttf
        - asset: assets/fonts/Cinzel-Bold.ttf
        - asset: assets/fonts/Cinzel-ExtraBold.ttf
        - asset: assets/fonts/Cinzel-Medium.ttf
        - asset: assets/fonts/Cinzel-Regular.ttf
        - asset: assets/fonts/Cinzel-SemiBold.ttf


    

